# docker-compose.yml
version: '3.8'

services:
  schedule-generator:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - schedule-db:/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  schedule-db: